language: cpp
python:
  - "2.7"
install:
  # Install ARM GCC
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt-get update
  - sudo apt-get install gcc-arm-embedded -y
  # Install yotta
  - pip install --user yotta
script:
  # Build all tests for frdm-k64f-gcc
  - yotta target frdm-k64f-gcc
  - yotta install
  - yotta build all_tests
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - g++-4.8
      - python-setuptools
      - cmake
      - build-essential
      - ninja-build
      - python-dev
      - libffi-dev
      - libssl-dev